IF NOT EXISTS
(
	SELECT TOP 1 1 FROM sys.databases WHERE NAME = 'PRD_DCSBHISTORICO'
)
	BEGIN
		CREATE DATABASE [PRD_DCSBHISTORICO]
		ON PRIMARY
		(
			NAME = N'[PRD_DCSBHISTORICO]', FILENAME = 'E:\DATA\PRD_DCSBHISTORICO.mdf',
			SIZE = 500 MB, FILEGROWTH = 500 MB
		)
		LOG ON
		(
			NAME =N'[PRD_DCSBHISTORICO.LOG]', FILENAME = 'F:\LOG\PRD_DCSBHISTORICO.ldf',
			SIZE = 100 MB, FILEGROWTH = 100 MB
		)
	END